name: ks-download
version: '2.2'
synopsis: Data downloader and parser for the KitchenSnitch project
description: Bar Baz
license: BSD3
author: Dino Morelli
maintainer: Dino Morelli <dino@ui3.info>
category: Unknown
extra-source-files:
- changelog.md
- README.md
- stack.yaml
# - util/inspconv.coffee
# - util/install.hs
# - util/ks-dl-nightly-cdp.sh
# - util/ks-dl-nightly-dhd.sh
# - util/resources/geocode.json
# - util/resources/nc-wake/searchResultPage.html
# - util/resources/places.json

# data-files:
# - resources/ks-download.conf
# - resources/ks-download-nc_chatham.conf
# - resources/ks-download-nc_durham.conf
# - resources/ks-download-nc_orange.conf
# - resources/ks-download-nc_wake.conf
# - resources/mongodb.conf

github: dino-/ks-download

ghc-options:
- -fwarn-tabs
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- BangPatterns
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
#- OverloadedStrings
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies


dependencies:

- base >=3 && <5


library:
  source-dirs: src/lib
  dependencies:
  - bytestring
  - exceptions
  - filepath
  - hslogger
  - HTTP
  - ks-library >=1.13
  - lens
  - mongoDB
  - mtl
  - regex-compat
  - tagsoup
  - tce-conf
  - text
  - time
  - wreq


executables:

  ks-dlinsp-cdp:
    main: Main.hs
    source-dirs: src/ks-dlinsp-cdp
    dependencies:
    - ks-download

  ks-dlinsp-dhd:
    main: Main.hs
    source-dirs: src/ks-dlinsp-dhd
    dependencies:
    - ks-download

  ks-locate:
    main: Main.hs
    source-dirs: src/ks-locate
    dependencies:
    - aeson
    - aeson-pretty
    - attoparsec
    - bytestring
    - directory
    - exceptions
    - filepath
    - hcoord
    - hslogger
    - hspec
    - HTTP
    - http-conduit
    - ks-download
    - ks-library
    - mtl
    - string-conv
    - regex-pcre
    - tce-conf
    - text

  ks-dbinsert:
    main: Main.hs
    source-dirs: src/ks-dbinsert
    dependencies:
    - bson-generic
    - directory
    - filepath
    - ks-download
    - ks-library
    - mongoDB
    - mtl
    - text

  ks-regionupd:
    main: Main.hs
    source-dirs: src/ks-regionupd
    dependencies:
    - aeson
    - bson
    - bytestring
    - ks-download
    - ks-library
    - mongoDB
    - mtl
    - regex-compat
    - safe-exceptions
    - text
    - time

  ks-clean:
    main: Main.hs
    source-dirs: src/ks-clean
    dependencies:
    - aeson
    - ansi-wl-pprint
    - bson
    - bson-generic
    - ks-download
    - ks-library >=1.13
    - lens
    - mongoDB
    - mtl
    - optparse-applicative
    - string-conv
    - text
    - time
    - wreq


tests:

  test-Locate:
    main: test-Locate.hs
    source-dirs:
    - src/ks-locate
    - testsuite
    dependencies:
    - aeson
    - attoparsec
    - bytestring
    - hcoord
    - hspec
    - HTTP
    - http-conduit
    - ks-download
    - ks-library
    - regex-pcre
    - string-conv
    - text
    - time
